name: hl23pyr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - lxml
  - jupyterlab
  - pip:
      - neuron==8.2.3
      - netpyne==1.1.1
      - efel==4.1.76